# Generated by Django 2.2 on 2019-04-11 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=20)),
                ('question_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('questions', models.ManyToManyField(related_name='question', to='battle.Questions', verbose_name='Questions')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_1', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_2', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
