# Generated by Django 2.2 on 2019-04-11 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0002_auto_20190411_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='WAITING', max_length=20),
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_correct_user_1', models.SmallIntegerField()),
                ('answers_correct_user_2', models.SmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='battle.Game', verbose_name='Game')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Game History',
                'verbose_name_plural': 'Game Histories',
            },
        ),
    ]
