# Generated by Django 2.2 on 2019-04-11 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_auto_20190411_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_1', to=settings.AUTH_USER_MODEL, verbose_name='User 1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_2', to=settings.AUTH_USER_MODEL, verbose_name='User 2'),
        ),
    ]
