# Generated by Django 2.2 on 2019-04-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20190411_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='battle.Game', verbose_name='Game'),
        ),
    ]
