# Generated by Django 2.2 on 2019-04-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_auto_20190414_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
    ]
