# Generated by Django 2.2 on 2019-04-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_auto_20190414_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='battle.Game', verbose_name='Game'),
        ),
    ]
